[package]
name = "cloudsql-autoscale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-cloud-gax = "0.14.1"
google-cloud-pubsub = "0.14.1"
tokio = { version="1.27.0", feature=["full"] }
